export const SET_FORMS = 'SET_FORMS';
export const SET_CURRENT_FORM = 'SET_CURRENT_FORM';
export const FETCH_FORMS_FAILED = 'FETCH_FORMS_FAILED';

export const EVADB_QUERY_INIT = 'EVADB_QUERY_INIT';
export const EVADB_QUERY_START = 'EVADB_QUERY_START';
export const EVADB_QUERY_SUCCESS = 'EVADB_QUERY_SUCCESS';
export const EVADB_QUERY_FAIL = 'EVADB_QUERY_FAIL';

