- section: Sample searches
  forms: 
  - title: Samples with quality
    fields:
      - type: chrom
        config:
          fixed: X
      - type: Pos
  - title: Samples
    fields:
      - function
      - foo 
- section: Variant searches
  forms:
  - title: Basic
    fields: 
      - chrom
      - pos_gt
      - pos_lt
      - cov_gt
  - title: Autosomal dominant
    fields:
      - chrom
      - pos_gt
      - pos_lt
      - function
      - foo 
      - abc
  - title: Autosomal recessive
    fields:
      - chrom
      - pos_gt
      - pos_lt
      - function
      - foo 
  - title: De novo trio
    fields:
      - chrom
      - pos_gt
      - pos_lt
  - title: Disease panels
    fields:
      - chrom
      - pos_gt
      - pos_lt
      - function
      - foo 
  - title: Genes
    fields:
      - chrom
      - pos_gt
      - pos_lt
      - function
      - foo 
  - title: ClinVar/HGMD
    fields:
      - chrom
      - pos_gt
      - pos_lt
      - function
      - foo 
  - title: OMIM
    fields:
      - chrom
      - pos_gt
      - pos_lt
      - function
      - foo 
  - title: HPO
    fields:
      - chrom
      - pos_gt
      - pos_lt
      - function
      - foo 
  - title: Tumor/Controls
    fields:
      - chrom
      - pos_gt
      - pos_lt
      - function
      - foo 
  - title: Same Variant
    fields:
      - chrom
      - pos_gt
      - pos_lt
      - function
      - foo 
  - title: Region
    fields: 
      - foo
- section: CNV
  forms:
  - title: CNV
    fields:
      - chrom
      - pos_gt
      - pos_lt
      - function
      - foo 
- section: Coverage
  forms:
  - title: Coverage of genes
    fields:
      - chrom
      - pos_gt
      - pos_lt
      - function
      - foo 
  - title: Coverage of panels
    fields:
      - chrom
      - pos_gt
      - pos_lt
      - function
      - foo 
- section: Other
  forms:
  - title: Homozygosity
    fields:
      - chrom
      - pos_gt
      - pos_lt
      - function
      - foo 
  - title: IBS
    fields:
      - chrom
      - pos_gt
      - pos_lt
      - function
      - foo 
  - title: Import HPO
    fields:
      - chrom
      - pos_gt
      - pos_lt
      - function
      - foo 
- section: Annotations/Report
  forms:
  - title: Variant annotations
    fields:
      - chrom
      - pos_gt
      - pos_lt
      - function
      - foo 
  - title: Case conclusions
    fields:
      - chrom
      - pos_gt
      - pos_lt
      - function
      - foo 
  - title: Report
    fields:
      - chrom
      - pos_gt
      - pos_lt
      - function
      - foo 
- section: My forms
  forms:
  - title: super query
    fields: 
      - chrom
      - foo
