// Generated by gt_filters.rb, do not edit

import QualityFilter from './QualityFilter'
import FunctionalFilter from './FunctionalFilter'

const filterMap = {
    QualityFilter: QualityFilter,
    FunctionalFilter: FunctionalFilter,
}

export default filterMap;
